<a href="https://colab.research.google.com/github/SatvikVarshney/Group1_Final_Project/blob/main/petrov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score


In [ ]:
df1=pd.read_csv("shuffledratio (3).csv", header=None)
df1 = df1.iloc[1:,1:]
print(df1)

         1  2  3  4   5    6
1        0 -1  0  0   0  III
2       -7  0  0  0  10    I
3        5  0  0 -6   0    I
4       -8  0  0  7   0    I
5        1  0  2  0   0   II
...     .. .. .. ..  ..  ...
329996 -10  0  0  0   9    I
329997   0  9  0 -2   0    I
329998   0  0  4  0   0    D
329999   0  0  0 -5   0  III
330000   0  0  7  0  -4   II

[330000 rows x 6 columns]


In [ ]:
def convert(y_val):
      if y_val == "O": y_val=0
      elif y_val == "I": y_val=1
      elif y_val == "II": y_val=2
      elif y_val == "III": y_val=3
      elif y_val == "D": y_val=4
      elif y_val == "N": y_val=5
      return y_val
      

In [ ]:
df1[6]=df1[6].apply(convert)

In [ ]:
print(df1)

         1  2  3  4   5  6
1        0 -1  0  0   0  3
2       -7  0  0  0  10  1
3        5  0  0 -6   0  1
4       -8  0  0  7   0  1
5        1  0  2  0   0  2
...     .. .. .. ..  .. ..
329996 -10  0  0  0   9  1
329997   0  9  0 -2   0  1
329998   0  0  4  0   0  4
329999   0  0  0 -5   0  3
330000   0  0  7  0  -4  2

[330000 rows x 6 columns]


In [ ]:
labels = np.array(df1[6])
result=df1.drop(columns=[6])
feature_list = list(result.columns)
result=np.array(result)


In [ ]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(result, labels, test_size = 0.25, random_state = 42, shuffle=True)

In [ ]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (247500, 5)
Training Labels Shape: (247500,)
Testing Features Shape: (82500, 5)
Testing Labels Shape: (82500,)


Random Forest

In [ ]:
# Import the model we are using
from sklearn.ensemble import RandomForestClassifier
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [ ]:
predictions = rf.predict(test_features)

In [ ]:
cm = confusion_matrix(test_labels, predictions)
print(cm)

[[ 2465     0     0     0     0     0]
 [    0 31477     0     0     0     0]
 [    0     0 22484     0     0     0]
 [    0     0     0 13895     0     0]
 [    0     0     0     0  6219     0]
 [    0     0     0     0     0  5960]]


In [ ]:
print(classification_report(test_labels,predictions))
print ("Accuracy : ",
    accuracy_score(test_labels,predictions)*100)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2465
           1       1.00      1.00      1.00     31477
           2       1.00      1.00      1.00     22484
           3       1.00      1.00      1.00     13895
           4       1.00      1.00      1.00      6219
           5       1.00      1.00      1.00      5960

    accuracy                           1.00     82500
   macro avg       1.00      1.00      1.00     82500
weighted avg       1.00      1.00      1.00     82500

Accuracy :  100.0


Decision tree

In [ ]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt


In [ ]:
features = [0,1,2,3,4]

In [ ]:
clf_gini = DecisionTreeClassifier(criterion = "entropy",
            random_state = 100,max_depth=30, min_samples_leaf=5)
clf_gini.fit(train_features, train_labels)

DecisionTreeClassifier(criterion='entropy', max_depth=30, min_samples_leaf=5,
                       random_state=100)

In [ ]:
y_pred = clf_gini.predict(test_features)
print("Confusion Matrix: \n",
        confusion_matrix(test_labels, y_pred))
      
print ("Accuracy : ",
    accuracy_score(test_labels,y_pred)*100)

Confusion Matrix: 
 [[ 2465     0     0     0     0     0]
 [    0 31477     0     0     0     0]
 [    0     0 22484     0     0     0]
 [    0     0     0 13895     0     0]
 [    0     0     0     0  6219     0]
 [    0     0     0     0     0  5960]]
Accuracy :  100.0


Nearest Neighbour

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(train_features, train_labels)

KNeighborsClassifier(n_neighbors=6)

In [ ]:
print(knn.score(test_features, test_labels))

0.9969454545454546


In [ ]:
y_pred = knn.predict(test_features)

In [ ]:
print("Confusion Matrix: \n",
        confusion_matrix(test_labels, y_pred))

Confusion Matrix: 
 [[ 2465     0     0     0     0     0]
 [    0 31248   229     0     0     0]
 [    0     0 22461    13    10     0]
 [    0     0     0 13895     0     0]
 [    0     0     0     0  6219     0]
 [    0     0     0     0     0  5960]]


In [ ]:
print ("Accuracy : ",
    accuracy_score(test_labels,y_pred)*100)

Accuracy :  99.69454545454546
